name: MCP Server CI (Rust)

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'mcp-rust/**'
      - '.github/workflows/mcp-server-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'mcp-rust/**'
      - '.github/workflows/mcp-server-ci.yml'

defaults:
  run:
    working-directory: ./mcp-rust

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust-version: ['1.90', 'stable', 'beta']  # MSRV, stable, and beta

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust ${{ matrix.rust-version }}
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: mcp-rust -> target

    - name: Format check
      run: cargo fmt --all -- --check

    - name: Clippy check
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --verbose

    - name: Test build
      run: cargo build --release

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Security audit
      run: cargo audit

    - name: Check for sensitive data
      run: |
        echo "Checking for sensitive data..."

        # Check for hardcoded secrets in Rust source
        if grep -r "baursoftware" src/ 2>/dev/null || grep -r "545027c4\|09c21e37" src/ 2>/dev/null; then
          echo "❌ Sensitive data found in source code"
          exit 1
        fi

        # Check for AWS credentials
        if grep -r -E "aws_access_key_id.*=.*[A-Z0-9]{20}" src/ 2>/dev/null; then
          echo "❌ Potential AWS access key found"
          exit 1
        fi

        if grep -r -E "aws_secret_access_key.*=.*[A-Za-z0-9/+=]{40}" src/ 2>/dev/null; then
          echo "❌ Potential AWS secret key found"
          exit 1
        fi

        echo "✅ No sensitive data found"

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: mcp-rust -> target

    - name: Build release binary
      run: cargo build --release

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: use_aws_mcp-binary
        path: target/release/use_aws_mcp*